--ozone-platform=wayland
--password-store=basic
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,TouchpadOverscrollHistoryNavigation
--process-per-site
